# Generated by Django 3.0.5 on 2021-10-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0003_auto_20211002_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
    ]
