# Generated by Django 3.0.5 on 2021-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0004_auto_20211002_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
