# Generated by Django 3.0.5 on 2021-10-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0005_auto_20211002_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='id',
            new_name='rider_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='id',
            new_name='rider_id',
        ),
    ]
