# Generated by Django 3.0.5 on 2021-10-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0007_rider_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ClickToEat.Order'),
        ),
    ]
