# Generated by Django 3.0.5 on 2021-10-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0009_auto_20211002_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='client',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='order',
        ),
        migrations.RemoveField(
            model_name='store',
            name='rider',
        ),
    ]
