# Generated by Django 3.0.5 on 2021-10-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0010_auto_20211003_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='rider_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_id',
            new_name='id',
        ),
    ]
