# Generated by Django 3.0.5 on 2021-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickToEat', '0011_auto_20211011_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Barangay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='House_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Municipality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Province',
            field=models.CharField(max_length=100),
        ),
    ]
